---
MD004: false # Unordered list style
MD007:
  indent: 2 # Unordered list indentation
MD013:
  line_length: 808 # Line length
  code_blocks: false
MD026:
  punctuation: '.,;:!。，；:' # List of not allowed
MD029: false # Ordered list item prefix
MD033: false # Allow inline HTML
MD036: false # Emphasis used instead of a heading
